# Generated by Django 4.0.5 on 2022-12-11 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_payments_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_date_of_payment',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 13, 17, 20, 865136)),
            preserve_default=False,
        ),
    ]
