# Generated by Django 4.0.5 on 2022-12-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_last_date_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_date_of_payment',
            field=models.DateTimeField(null=True),
        ),
    ]
